version: 2
models:
  - name: silver_fundamentals_pit
    columns:
      - name: cik
        tests: 
          - unique
          - not_null
      - name: metric_tag
        tests:
          - not_null
      - name: unit_of_measure
        tests:
          - unique
      - name: period_start_date
        tests:
          - unique
      - name: period_end_date
        tests:
          - unique 
          - not_null
      - name: filing_date
        tests: [not_null]
