version: 2
models:
  - name: silver_fundamentals_pit
    columns:
      - name: cik
        tests: [not_null]
      - name: metric_tag
        tests: [not_null]
      - name: period_end_date
        tests: [not_null]
      - name: available_date
        tests: [not_null]
  - name: silver_price_adjusted
    columns:
      - name: ticker
        tests: [not_null]
      - name: trade_date
        tests: [not_null]
      - name: adjusted_close_price
        tests: 
          - not_null