version: 2
models:
  - name: stg_price_eod
    columns:
      - name: ticker
        tests: [not_null]
      - name: trade_date
        tests: [not_null]
  - name: stg_fundamentals
    columns:
      - name: cik
        tests: [not_null]
      - name: filing_date
        tests: [not_null]
      - name: period_end_date
        tests: [not_null]
      - name: filing_type
        tests:
          - accepted_values:
              arguments:
                values: ["10-K", "10-Q"]
  - name: stg_sector
    columns:
      - name: ticker
        tests: [not_null]
      - name: sector
        tests: [not_null]