version: 2

models:
  - name: bronze_price_eod
    columns:
      - name: "Ticker"
        tests: [not_null]
      - name: "Date"
        tests: [not_null]

  - name: bronze_company_facts
    columns:
      - name: "cik"
        tests: [not_null]
      - name: filing_date
        tests: [not_null]
      - name: period_end
        tests: [not_null]
  - name: bronze_index_membership
    columns:
      - name: "Ticker"
        tests: [not_null]
      - name: "CIK"
        tests: [not_null]
